name: vinn_kurye
description: "VIP Kurye, şehir içi acil teslimat ihtiyacını teknoloji destekli, güvenli ve kullanıcı dostu bir deneyimle çözmeyi amaçlayan yeni nesil bir mobil teslimat platformudur."
# authors:
#    - Mehmet Akif Akkoç <info@mefamex.com> (https://mefamex.com) [https://github.com/Mefamex]
#    - Halil Temur

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    firebase_core: ^4.0.0
    firebase_auth: ^6.0.0
    cloud_firestore: ^6.0.0
    firebase_storage: ^13.0.0
    firebase_messaging: ^16.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    flutter_launcher_icons: ^0.14.4

flutter:
    uses-material-design: true
    assets:
        - assets/images/logos/
        - assets/images/backgrounds/
        - pubspec.yaml

flutter_icons:
    # cmd -> flutter pub run flutter_launcher_icons:main
    android: true
    # ios: true
    image_path: "assets/images/logos/icon_mini_min_512.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/logos/icon_mini_min_512.png"
    # remove_alpha_ios: true
    remove_alpha_android: true